#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
//#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000


#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_42
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_41
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_44
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_2
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_43

#define R_LED_GPIO        GPIO_NUM_3 
#define G_LED_GPIO        GPIO_NUM_4  
#define B_LED_GPIO        GPIO_NUM_5  

#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_6

#endif // _BOARD_CONFIG_H_
